version: "3"
services:
  api:
    image: ahmadnabi816/task-scheduler:1.0
    ports:
      - "8080:8080"
    environment:
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mongodb
    networks:
      - go-network

  mongodb:
    image: mvertes/alpine-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    volumes:
      - mongodb:/var/lib/mongodb/data
    networks:
      - go-network

volumes:
  mongodb:

networks:
  go-network:
    driver: bridge

