swagger: "2.0"
info:
  title: Task Scheduler
  description: Task scheduler api with go aims to schedule tasks based on a specific time
  version: 1.0.0
host: localhost:8080
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /task:
    post:
      operationId: "addTask"
      parameters:
        - in: "body"
          name: "task"
          description: "task's details"
          required: true
          schema:
            $ref: "#/definitions/Task"
      responses:
        201:
          description: "task added"
          schema:
            $ref: "#/definitions/Task"
        409:
          description: "task already exists"
        500:
          description: "internal server error"
    put:
      operationId: "updateTask"
      parameters:
        - in: "body"
          name: "task"
          required: true
          description: "task details"
          schema:
            $ref: "#/definitions/Task"
      responses:
        200:
          description: "task updated"
          schema:
            $ref: "#/definitions/Task"
        404:
          description: "tasks not found"
        500:
          description: "internal server error"
    get:
      operationId: "listTasks"
      description: "return tasks"
      responses:
        200:
          description: "tasks response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
        404:
          description: "tasks not found"
        500:
          description: "internal server error"

  /task/{ID}:
    delete:
      operationId: "deleteTask"
      parameters:
        - in: "path"
          name: "ID"
          type: "string"
          description: "ID of the task"
          required: true
      responses:
        204:
          description: "task deleted"
        404:
          description: "task not found"
        500:
          description: "internal server error"
    get:
      operationId: "getTaskByID"
      parameters:
        - in: "path"
          name: "ID"
          type: "string"
          description: "task by id"
          required: true
      responses:
        200:
          description: "task response"
          schema:
            $ref: "#/definitions/Task"
        404:
          description: "task not found"
        500:
          description: "internal server error"
definitions:
  Task:
    type: "object"
    properties:
      ID:
        type: "string"
      Name:
        type: "string"
      Command:
        type: "string"
      ScheduledTime:
        type: "string"
        format: "date-time"
        description: "The scheduled date and time for the task "
      Recurring:
        type: "boolean"
      TimeZone:
        type: "string"
